# Generated by Django 5.2.4 on 2025-07-13 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_group_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
