# Generated by Django 5.2.4 on 2025-07-13 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.CharField(max_length=100)),
                ('state', models.IntegerField(choices=[(1, "To'lov yaratildi. Tasdiqlanishi kutilmoqda"), (2, "To'lov amalga muvafaqqiyatli amalga oshirildi"), (-1, "To'lov bekor qilindi"), (-2, "To'lov tugallangandan keyin qaytarildi.")])),
                ('amount', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
