# Generated by Django 5.2.4 on 2025-07-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/users', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='user',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qishloq'),
        ),
    ]
