# Generated by Django 5.2.4 on 2025-07-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_image_alter_user_village'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Guruh', 'verbose_name_plural': 'Guruhlar'},
        ),
        migrations.AlterModelOptions(
            name='invite',
            options={'verbose_name': 'Taklif', 'verbose_name_plural': 'Takliflar'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': "To'lov", 'verbose_name_plural': "To'lovlar"},
        ),
    ]
