# Generated by Django 5.2.4 on 2025-07-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_group_options_alter_invite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
