# Generated by Django 5.2.4 on 2025-08-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_group_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='max_members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='price',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], default='income', max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.IntegerField(choices=[(1, "To'lov yaratildi. Tasdiqlanishi kutilmoqda"), (2, "To'lov amalga muvafaqqiyatli amalga oshirildi"), (-1, "To'lov bekor qilindi"), (-2, "To'lov tugallangandan keyin qaytarildi."), (3, 'Yechib olindi')]),
        ),
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
