# Generated by Django 5.2.4 on 2025-08-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_group_max_members_remove_group_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Otasining ismi'),
            preserve_default=False,
        ),
    ]
