# Generated by Django 5.2.4 on 2025-07-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.TextField(),
        ),
    ]
