# Generated by Django 5.2.4 on 2025-07-13 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='subject',
        ),
    ]
