# Generated by Django 5.2.4 on 2025-07-13 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_remove_test_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/answers'),
        ),
        migrations.AlterField(
            model_name='dtm',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='dtm_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
