# Generated by Django 5.2.4 on 2025-07-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_answer_image_alter_dtm_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtm',
            name='id_open',
            field=models.BooleanField(default=False),
        ),
    ]
