# Generated by Django 5.2.4 on 2025-07-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_dtm_id_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtm',
            name='id_open',
        ),
    ]
