# Generated by Django 5.2.4 on 2025-07-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_remove_dtm_id_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtm',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
