# Generated by Django 5.2.4 on 2025-07-17 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_dtm_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cefr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_public', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField()),
                ('ended', models.DateTimeField()),
                ('participants', models.ManyToManyField(blank=True, related_name='cefr_participants', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.subject')),
            ],
            options={
                'verbose_name': 'CEFR',
                'verbose_name_plural': 'CEFR lar',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/tests')),
                ('type', models.CharField(choices=[('single', 'Bitta javob tanlanadigan'), ('multiple', "Ko'p javob tanlanadigan"), ('matchable', 'Moslashtiriladigan'), ('writable', 'Javob yoziladigan')], max_length=10)),
                ('cefr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.block')),
            ],
            options={
                'verbose_name': 'CEFR savoli',
                'verbose_name_plural': 'CEFR savollari',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_1', models.TextField()),
                ('value_2', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/answers')),
                ('is_correct', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
            options={
                'verbose_name': 'CEFR savoli javobi',
                'verbose_name_plural': 'CEFR savoli javoblari',
            },
        ),
    ]
