# Generated by Django 5.2.4 on 2025-07-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_remove_questionanswer_test_questionanswer_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'DTM test javob', 'verbose_name_plural': 'DTM test javoblari'},
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': 'DTM blok', 'verbose_name_plural': 'DTM bloklar'},
        ),
        migrations.AlterModelOptions(
            name='dtm',
            options={'verbose_name': 'DTM', 'verbose_name_plural': 'DTM lar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'DTM test', 'verbose_name_plural': 'DTM testlar'},
        ),
    ]
