# Generated by Django 5.2.4 on 2025-07-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_alter_answer_options_alter_block_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='cefr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.cefr'),
        ),
    ]
