# Generated by Django 5.2.4 on 2025-07-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
