# Generated by Django 5.2.4 on 2025-07-28 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_banner_is_active'),
        ('users', '0006_alter_group_options_alter_invite_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cefr',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group'),
        ),
        migrations.AddField(
            model_name='cefr',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dtm',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group'),
        ),
        migrations.AddField(
            model_name='dtm',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CEFRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.JSONField(default=dict)),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('degree', models.CharField(choices=[('a', 'A'), ('a+', 'A+'), ('b', 'B'), ('b+', 'B+'), ('c', 'C'), ('c+', 'C+'), ('d', 'D'), ('d+', 'D+'), ('f', 'F'), ('f+', 'F+')], max_length=5)),
                ('status', models.CharField(choices=[('failed', 'Yiqilgan'), ('passed', "O'tgan")], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cefr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.cefr')),
            ],
        ),
        migrations.CreateModel(
            name='DTMResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases', models.JSONField(default=dict)),
                ('points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('failed', 'Yiqilgan'), ('passed', "O'tgan")], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dtm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.dtm')),
            ],
        ),
    ]
