# Generated by Django 5.2.4 on 2025-07-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_cefr_group_cefr_passing_score_dtm_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cefr',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dtm',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
