# Generated by Django 5.2.4 on 2025-07-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_cefr_price_dtm_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cefrresult',
            name='degree',
            field=models.CharField(choices=[('a', 'A'), ('a+', 'A+'), ('b', 'B'), ('b+', 'B+'), ('c', 'C'), ('c+', 'C+'), ('d', 'D'), ('d+', 'D+'), ('f', 'F'), ('f+', 'F+'), ('nc', 'Hisoblanmagan')], default='nc', max_length=5),
        ),
        migrations.AlterField(
            model_name='cefrresult',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cefrresult',
            name='status',
            field=models.CharField(blank=True, choices=[('failed', 'Yiqilgan'), ('passed', "O'tgan")], max_length=10, null=True),
        ),
    ]
