# Generated by Django 5.2.4 on 2025-08-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_alter_cefrresult_degree_alter_cefrresult_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='ball',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=10),
        ),
    ]
