# Generated by Django 5.2.4 on 2025-08-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_block_ball'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cefrresult',
            name='status',
            field=models.CharField(blank=True, choices=[('calculating', 'Hisoblanmoqda'), ('failed', 'Yiqilgan'), ('passed', "O'tgan")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dtmresult',
            name='status',
            field=models.CharField(choices=[('calculating', 'Hisoblanmoqda'), ('failed', 'Yiqilgan'), ('passed', "O'tgan")], max_length=20),
        ),
    ]
