# Generated by Django 5.2.4 on 2025-08-10 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_alter_cefrresult_status_alter_dtmresult_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cefrresult',
            old_name='points',
            new_name='according_to_the_answers_found',
        ),
        migrations.AddField(
            model_name='cefr',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cefrresult',
            name='by_difficulty_level',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cefrresult',
            name='deviation',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cefrresult',
            name='rash',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cefrresult',
            name='ratio_of_total_questions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Rash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rash/results')),
                ('status', models.CharField(choices=[('done', 'Hisoblangan'), ('waiting', 'Hisoblanmoqda')], default='waiting', max_length=10)),
                ('cefr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.cefr')),
            ],
        ),
    ]
