# Generated by Django 5.2.4 on 2025-08-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0020_rename_points_cefrresult_according_to_the_answers_found_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rash',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='rash/results'),
        ),
    ]
