# Generated by Django 5.2.4 on 2025-08-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0021_alter_rash_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cefrresult',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
