# Generated by Django 5.2.4 on 2025-08-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0022_cefrresult_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cefrresult',
            name='degree',
            field=models.CharField(default='nc', max_length=5),
        ),
    ]
