# Generated by Django 5.2.4 on 2025-08-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0023_alter_cefrresult_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cefrresult',
            name='degree',
            field=models.CharField(choices=[('A', 'A'), ('A+', 'A+'), ('B', 'B'), ('B+', 'B+'), ('C', 'C'), ('C+', 'C+'), ('D', 'D'), ('D+', 'D+'), ('F', 'F'), ('F+', 'F+'), ('nc', 'Hisoblanmagan')], default='nc', max_length=5),
        ),
    ]
