# Generated by Django 5.2.4 on 2025-08-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_alter_cefrresult_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cefr',
            name='group',
        ),
        migrations.RemoveField(
            model_name='dtm',
            name='group',
        ),
        migrations.AddField(
            model_name='cefrresult',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates'),
        ),
        migrations.AddField(
            model_name='dtmresult',
            name='answers_sheet',
            field=models.FileField(blank=True, null=True, upload_to='answers_sheets'),
        ),
    ]
