# Generated by Django 5.2.4 on 2025-08-10 13:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0025_remove_cefr_group_remove_dtm_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cefr',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='dtm',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
