# Generated by Django 5.2.4 on 2025-08-10 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0027_dtmresult_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cefrresult',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cefr_result_teacher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
