# Generated by Django 5.2.4 on 2025-08-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0028_cefrresult_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': "E'lon", 'verbose_name_plural': "E'lonlar"},
        ),
        migrations.AlterModelOptions(
            name='cefrresult',
            options={'verbose_name': 'CEFR natija', 'verbose_name_plural': 'CEFR natijalar'},
        ),
        migrations.AlterModelOptions(
            name='dtmresult',
            options={'verbose_name': 'DTM natija', 'verbose_name_plural': 'DTM natijalar'},
        ),
        migrations.AlterModelOptions(
            name='rash',
            options={'verbose_name': 'RASH', 'verbose_name_plural': 'RASH'},
        ),
    ]
