# Generated by Django 5.2.4 on 2025-08-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0029_alter_banner_options_alter_cefrresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cefrresult',
            name='percentage',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
