# Generated by Django 5.2.4 on 2025-08-29 05:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0031_answer_author_block_author_cefr_author_dtm_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='author',
        ),
        migrations.AlterField(
            model_name='cefr',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='dtm',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
