# Generated by Django 5.2.4 on 2025-09-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0032_remove_subject_author_alter_cefr_uuid_alter_dtm_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
    ]
