# Generated by Django 5.2.4 on 2025-09-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0033_remove_answer_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='author',
        ),
    ]
